name: Build Artifact

on:
    workflow_call:  # Allows this workflow to be called from another workflow
      outputs:
        artifact_name:
          description: "Name of the built artifact"
          value: "my-artifact"

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build container image
        run: |
          docker build -t rockpro64_uboot -f Dockerfile.arm64 .

      - name: Run container and copy artifact
        run: |
          docker run --rm -v $PWD:/src rockpro64_uboot

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: release/*  # Adjust to match your artifact output location