name: Release Artifact

on:
  push:
    tags:
      - "v*"  # Runs only when pushing a version tag like "v1.0.0"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: release-assets

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}  # Uses the pushed tag
          name: "Release ${{ github.ref_name }}"
          body: "Automated release of built artifact."
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: release-assets/*
          token: ${{ secrets.GITHUB_TOKEN }}
